# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CertificateAddToken(BaseModel):
    """
    CertificateAddToken
    """ # noqa: E501
    addresses: Optional[List[StrictStr]] = Field(default=None, description="The addresses of the server", json_schema_extra={"examples": [["10.98.30.229:8443"]]})
    client_name: Optional[StrictStr] = Field(default=None, description="The name of the new client", json_schema_extra={"examples": ["user@host"]})
    expires_at: Optional[datetime] = Field(default=None, description="The token's expiry date.", json_schema_extra={"examples": ["2021-03-23T17:38:37.753398689-04:00"]})
    fingerprint: Optional[StrictStr] = Field(default=None, description="The fingerprint of the network certificate", json_schema_extra={"examples": ["57bb0ff4340b5bb28517e062023101adf788c37846dc8b619eb2c3cb4ef29436"]})
    secret: Optional[StrictStr] = Field(default=None, description="The random join secret", json_schema_extra={"examples": ["2b2284d44db32675923fe0d2020477e0e9be11801ff70c435e032b97028c35cd"]})
    __properties: ClassVar[List[str]] = ["addresses", "client_name", "expires_at", "fingerprint", "secret"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CertificateAddToken from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CertificateAddToken from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "addresses": obj.get("addresses"),
            "client_name": obj.get("client_name"),
            "expires_at": obj.get("expires_at"),
            "fingerprint": obj.get("fingerprint"),
            "secret": obj.get("secret")
        })
        return _obj


