# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.image_alias import ImageAlias
from pyincusd.models.image_source import ImageSource
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Image(BaseModel):
    """
    Image represents an image
    """ # noqa: E501
    aliases: Optional[List[ImageAlias]] = Field(default=None, description="List of aliases")
    architecture: Optional[StrictStr] = Field(default=None, description="Architecture")
    auto_update: Optional[StrictBool] = Field(default=None, description="Whether the image should auto-update when a new build is available")
    cached: Optional[StrictBool] = Field(default=None, description="Whether the image is an automatically cached remote image")
    created_at: Optional[datetime] = Field(default=None, description="When the image was originally created")
    expires_at: Optional[datetime] = Field(default=None, description="When the image becomes obsolete")
    filename: Optional[StrictStr] = Field(default=None, description="Original filename")
    fingerprint: Optional[StrictStr] = Field(default=None, description="Full SHA-256 fingerprint")
    last_used_at: Optional[datetime] = Field(default=None, description="Last time the image was used")
    profiles: Optional[List[StrictStr]] = Field(default=None, description="List of profiles to use when creating from this image (if none provided by user)")
    project: Optional[StrictStr] = Field(default=None, description="Project name")
    properties: Optional[Dict[str, StrictStr]] = Field(default=None, description="Descriptive properties")
    public: Optional[StrictBool] = Field(default=None, description="Whether the image is available to unauthenticated users")
    size: Optional[StrictInt] = Field(default=None, description="Size of the image in bytes")
    type: Optional[StrictStr] = Field(default=None, description="Type of image (container or virtual-machine)")
    update_source: Optional[ImageSource] = None
    uploaded_at: Optional[datetime] = Field(default=None, description="When the image was added to this server")
    __properties: ClassVar[List[str]] = ["aliases", "architecture", "auto_update", "cached", "created_at", "expires_at", "filename", "fingerprint", "last_used_at", "profiles", "project", "properties", "public", "size", "type", "update_source", "uploaded_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Image from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in aliases (list)
        _items = []
        if self.aliases:
            for _item_aliases in self.aliases:
                if _item_aliases:
                    _items.append(_item_aliases.to_dict())
            _dict['aliases'] = _items
        # override the default output from pydantic by calling `to_dict()` of update_source
        if self.update_source:
            _dict['update_source'] = self.update_source.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Image from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "aliases": [ImageAlias.from_dict(_item) for _item in obj["aliases"]] if obj.get("aliases") is not None else None,
            "architecture": obj.get("architecture"),
            "auto_update": obj.get("auto_update"),
            "cached": obj.get("cached"),
            "created_at": obj.get("created_at"),
            "expires_at": obj.get("expires_at"),
            "filename": obj.get("filename"),
            "fingerprint": obj.get("fingerprint"),
            "last_used_at": obj.get("last_used_at"),
            "profiles": obj.get("profiles"),
            "project": obj.get("project"),
            "properties": obj.get("properties"),
            "public": obj.get("public"),
            "size": obj.get("size"),
            "type": obj.get("type"),
            "update_source": ImageSource.from_dict(obj["update_source"]) if obj.get("update_source") is not None else None,
            "uploaded_at": obj.get("uploaded_at")
        })
        return _obj


