# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ImagesPostSource(BaseModel):
    """
    ImagesPostSource represents the source of a new image
    """ # noqa: E501
    alias: Optional[StrictStr] = Field(default=None, description="Source alias to download from")
    certificate: Optional[StrictStr] = Field(default=None, description="Source server certificate (if not trusted by system CA)")
    fingerprint: Optional[StrictStr] = Field(default=None, description="Source image fingerprint (for type \"image\")")
    image_type: Optional[StrictStr] = Field(default=None, description="Type of image (container or virtual-machine)")
    mode: Optional[StrictStr] = Field(default=None, description="Transfer mode (push or pull)")
    name: Optional[StrictStr] = Field(default=None, description="Instance name (for type \"instance\" or \"snapshot\")")
    project: Optional[StrictStr] = Field(default=None, description="Source project name")
    protocol: Optional[StrictStr] = Field(default=None, description="Source server protocol")
    secret: Optional[StrictStr] = Field(default=None, description="Source image server secret token (when downloading private images)")
    server: Optional[StrictStr] = Field(default=None, description="URL of the source server")
    type: Optional[StrictStr] = Field(default=None, description="Type of image source (instance, snapshot, image or url)")
    url: Optional[StrictStr] = Field(default=None, description="Source URL (for type \"url\")")
    __properties: ClassVar[List[str]] = ["alias", "certificate", "fingerprint", "image_type", "mode", "name", "project", "protocol", "secret", "server", "type", "url"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ImagesPostSource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ImagesPostSource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alias": obj.get("alias"),
            "certificate": obj.get("certificate"),
            "fingerprint": obj.get("fingerprint"),
            "image_type": obj.get("image_type"),
            "mode": obj.get("mode"),
            "name": obj.get("name"),
            "project": obj.get("project"),
            "protocol": obj.get("protocol"),
            "secret": obj.get("secret"),
            "server": obj.get("server"),
            "type": obj.get("type"),
            "url": obj.get("url")
        })
        return _obj


