# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.instance_backup import InstanceBackup
from pyincusd.models.instance_snapshot import InstanceSnapshot
from pyincusd.models.instance_state import InstanceState
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InstanceFull(BaseModel):
    """
    InstanceFull
    """ # noqa: E501
    architecture: Optional[StrictStr] = Field(default=None, description="Architecture name")
    backups: Optional[List[InstanceBackup]] = Field(default=None, description="List of backups.")
    config: Optional[Dict[str, Any]] = Field(default=None, description="Instance configuration (see doc/instances.md)")
    created_at: Optional[datetime] = Field(default=None, description="Instance creation timestamp")
    description: Optional[StrictStr] = Field(default=None, description="Instance description")
    devices: Optional[Dict[str, Any]] = Field(default=None, description="Instance devices (see doc/instances.md)")
    disk_only: Optional[StrictBool] = Field(default=None, description="Whether only the instances disk should be restored")
    ephemeral: Optional[StrictBool] = Field(default=None, description="Whether the instance is ephemeral (deleted on shutdown)")
    expanded_config: Optional[Dict[str, Any]] = Field(default=None, description="Expanded configuration (all profiles and local config merged)")
    expanded_devices: Optional[Dict[str, Any]] = Field(default=None, description="Expanded devices (all profiles and local devices merged)")
    last_used_at: Optional[datetime] = Field(default=None, description="Last start timestamp")
    location: Optional[StrictStr] = Field(default=None, description="What cluster member this instance is located on")
    name: Optional[StrictStr] = Field(default=None, description="Instance name")
    profiles: Optional[List[StrictStr]] = Field(default=None, description="List of profiles applied to the instance")
    project: Optional[StrictStr] = Field(default=None, description="Instance project name")
    restore: Optional[StrictStr] = Field(default=None, description="If set, instance will be restored to the provided snapshot name")
    snapshots: Optional[List[InstanceSnapshot]] = Field(default=None, description="List of snapshots.")
    state: Optional[InstanceState] = None
    stateful: Optional[StrictBool] = Field(default=None, description="Whether the instance currently has saved state on disk")
    status: Optional[StrictStr] = Field(default=None, description="Instance status (see instance_state)")
    status_code: Optional[StrictInt] = None
    type: Optional[StrictStr] = Field(default=None, description="The type of instance (container or virtual-machine)")
    __properties: ClassVar[List[str]] = ["architecture", "backups", "config", "created_at", "description", "devices", "disk_only", "ephemeral", "expanded_config", "expanded_devices", "last_used_at", "location", "name", "profiles", "project", "restore", "snapshots", "state", "stateful", "status", "status_code", "type"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InstanceFull from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in backups (list)
        _items = []
        if self.backups:
            for _item_backups in self.backups:
                if _item_backups:
                    _items.append(_item_backups.to_dict())
            _dict['backups'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in snapshots (list)
        _items = []
        if self.snapshots:
            for _item_snapshots in self.snapshots:
                if _item_snapshots:
                    _items.append(_item_snapshots.to_dict())
            _dict['snapshots'] = _items
        # override the default output from pydantic by calling `to_dict()` of state
        if self.state:
            _dict['state'] = self.state.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InstanceFull from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "architecture": obj.get("architecture"),
            "backups": [InstanceBackup.from_dict(_item) for _item in obj["backups"]] if obj.get("backups") is not None else None,
            "config": obj.get("config"),
            "created_at": obj.get("created_at"),
            "description": obj.get("description"),
            "devices": obj.get("devices"),
            "disk_only": obj.get("disk_only"),
            "ephemeral": obj.get("ephemeral"),
            "expanded_config": obj.get("expanded_config"),
            "expanded_devices": obj.get("expanded_devices"),
            "last_used_at": obj.get("last_used_at"),
            "location": obj.get("location"),
            "name": obj.get("name"),
            "profiles": obj.get("profiles"),
            "project": obj.get("project"),
            "restore": obj.get("restore"),
            "snapshots": [InstanceSnapshot.from_dict(_item) for _item in obj["snapshots"]] if obj.get("snapshots") is not None else None,
            "state": InstanceState.from_dict(obj["state"]) if obj.get("state") is not None else None,
            "stateful": obj.get("stateful"),
            "status": obj.get("status"),
            "status_code": obj.get("status_code"),
            "type": obj.get("type")
        })
        return _obj


