# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InstanceSnapshot(BaseModel):
    """
    InstanceSnapshot
    """ # noqa: E501
    architecture: Optional[StrictStr] = Field(default=None, description="Architecture name")
    config: Optional[Dict[str, Any]] = Field(default=None, description="Instance configuration (see doc/instances.md)")
    created_at: Optional[datetime] = Field(default=None, description="Instance creation timestamp")
    description: Optional[StrictStr] = Field(default=None, description="Instance description")
    devices: Optional[Dict[str, Any]] = Field(default=None, description="Instance devices (see doc/instances.md)")
    ephemeral: Optional[StrictBool] = Field(default=None, description="Whether the instance is ephemeral (deleted on shutdown)")
    expanded_config: Optional[Dict[str, Any]] = Field(default=None, description="Expanded configuration (all profiles and local config merged)")
    expanded_devices: Optional[Dict[str, Any]] = Field(default=None, description="Expanded devices (all profiles and local devices merged)")
    expires_at: Optional[datetime] = Field(default=None, description="When the snapshot expires (gets auto-deleted)")
    last_used_at: Optional[datetime] = Field(default=None, description="Last start timestamp")
    name: Optional[StrictStr] = Field(default=None, description="Snapshot name")
    profiles: Optional[List[StrictStr]] = Field(default=None, description="List of profiles applied to the instance")
    size: Optional[StrictInt] = Field(default=None, description="Size of the snapshot in bytes")
    stateful: Optional[StrictBool] = Field(default=None, description="Whether the instance currently has saved state on disk")
    __properties: ClassVar[List[str]] = ["architecture", "config", "created_at", "description", "devices", "ephemeral", "expanded_config", "expanded_devices", "expires_at", "last_used_at", "name", "profiles", "size", "stateful"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InstanceSnapshot from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InstanceSnapshot from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "architecture": obj.get("architecture"),
            "config": obj.get("config"),
            "created_at": obj.get("created_at"),
            "description": obj.get("description"),
            "devices": obj.get("devices"),
            "ephemeral": obj.get("ephemeral"),
            "expanded_config": obj.get("expanded_config"),
            "expanded_devices": obj.get("expanded_devices"),
            "expires_at": obj.get("expires_at"),
            "last_used_at": obj.get("last_used_at"),
            "name": obj.get("name"),
            "profiles": obj.get("profiles"),
            "size": obj.get("size"),
            "stateful": obj.get("stateful")
        })
        return _obj


