# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InstanceExecPost(BaseModel):
    """
    InstanceExecPost
    """ # noqa: E501
    command: Optional[List[StrictStr]] = Field(default=None, description="Command and its arguments")
    cwd: Optional[StrictStr] = Field(default=None, description="Current working directory for the command")
    environment: Optional[Dict[str, StrictStr]] = Field(default=None, description="Additional environment to pass to the command")
    group: Optional[StrictInt] = Field(default=None, description="GID of the user to spawn the command as")
    height: Optional[StrictInt] = Field(default=None, description="Terminal height in rows (for interactive)")
    interactive: Optional[StrictBool] = Field(default=None, description="Whether the command is to be spawned in interactive mode (singled PTY instead of 3 PIPEs)")
    record_output: Optional[StrictBool] = Field(default=None, description="Whether to capture the output for later download (requires non-interactive)", alias="record-output")
    user: Optional[StrictInt] = Field(default=None, description="UID of the user to spawn the command as")
    wait_for_websocket: Optional[StrictBool] = Field(default=None, description="Whether to wait for all websockets to be connected before spawning the command", alias="wait-for-websocket")
    width: Optional[StrictInt] = Field(default=None, description="Terminal width in characters (for interactive)")
    __properties: ClassVar[List[str]] = ["command", "cwd", "environment", "group", "height", "interactive", "record-output", "user", "wait-for-websocket", "width"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InstanceExecPost from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InstanceExecPost from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "command": obj.get("command"),
            "cwd": obj.get("cwd"),
            "environment": obj.get("environment"),
            "group": obj.get("group"),
            "height": obj.get("height"),
            "interactive": obj.get("interactive"),
            "record-output": obj.get("record-output"),
            "user": obj.get("user"),
            "wait-for-websocket": obj.get("wait-for-websocket"),
            "width": obj.get("width")
        })
        return _obj


