# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InstanceSource(BaseModel):
    """
    InstanceSource
    """ # noqa: E501
    alias: Optional[StrictStr] = Field(default=None, description="Image alias name (for image source)")
    allow_inconsistent: Optional[StrictBool] = Field(default=None, description="Whether to ignore errors when copying (e.g. for volatile files)")
    base_image: Optional[StrictStr] = Field(default=None, description="Base image fingerprint (for faster migration)", alias="base-image")
    certificate: Optional[StrictStr] = Field(default=None, description="Certificate (for remote images or migration)")
    fingerprint: Optional[StrictStr] = Field(default=None, description="Image fingerprint (for image source)")
    instance_only: Optional[StrictBool] = Field(default=None, description="Whether the copy should skip the snapshots (for copy)")
    live: Optional[StrictBool] = Field(default=None, description="Whether this is a live migration (for migration)")
    mode: Optional[StrictStr] = Field(default=None, description="Whether to use pull or push mode (for migration)")
    operation: Optional[StrictStr] = Field(default=None, description="Remote operation URL (for migration)")
    project: Optional[StrictStr] = Field(default=None, description="Source project name (for copy and local image)")
    properties: Optional[Dict[str, StrictStr]] = Field(default=None, description="Image filters (for image source)")
    protocol: Optional[StrictStr] = Field(default=None, description="Protocol name (for remote image)")
    refresh: Optional[StrictBool] = Field(default=None, description="Whether this is refreshing an existing instance (for migration and copy)")
    refresh_exclude_older: Optional[StrictBool] = Field(default=None, description="Whether to exclude source snapshots earlier than latest target snapshot")
    secret: Optional[StrictStr] = Field(default=None, description="Remote server secret (for remote private images)")
    secrets: Optional[Dict[str, StrictStr]] = Field(default=None, description="Map of migration websockets (for migration)")
    server: Optional[StrictStr] = Field(default=None, description="Remote server URL (for remote images)")
    source: Optional[StrictStr] = Field(default=None, description="Existing instance name or snapshot (for copy)")
    type: Optional[StrictStr] = Field(default=None, description="Source type")
    __properties: ClassVar[List[str]] = ["alias", "allow_inconsistent", "base-image", "certificate", "fingerprint", "instance_only", "live", "mode", "operation", "project", "properties", "protocol", "refresh", "refresh_exclude_older", "secret", "secrets", "server", "source", "type"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InstanceSource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InstanceSource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alias": obj.get("alias"),
            "allow_inconsistent": obj.get("allow_inconsistent"),
            "base-image": obj.get("base-image"),
            "certificate": obj.get("certificate"),
            "fingerprint": obj.get("fingerprint"),
            "instance_only": obj.get("instance_only"),
            "live": obj.get("live"),
            "mode": obj.get("mode"),
            "operation": obj.get("operation"),
            "project": obj.get("project"),
            "properties": obj.get("properties"),
            "protocol": obj.get("protocol"),
            "refresh": obj.get("refresh"),
            "refresh_exclude_older": obj.get("refresh_exclude_older"),
            "secret": obj.get("secret"),
            "secrets": obj.get("secrets"),
            "server": obj.get("server"),
            "source": obj.get("source"),
            "type": obj.get("type")
        })
        return _obj


