# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NetworkACLRule(BaseModel):
    """
    Refer to doc/network-acls.md for details.
    """ # noqa: E501
    action: Optional[StrictStr] = Field(default=None, description="Action to perform on rule match")
    description: Optional[StrictStr] = Field(default=None, description="Description of the rule")
    destination: Optional[StrictStr] = Field(default=None, description="Destination address")
    destination_port: Optional[StrictStr] = Field(default=None, description="Destination port")
    icmp_code: Optional[StrictStr] = Field(default=None, description="ICMP message code (for ICMP protocol)")
    icmp_type: Optional[StrictStr] = Field(default=None, description="Type of ICMP message (for ICMP protocol)")
    protocol: Optional[StrictStr] = Field(default=None, description="Protocol")
    source: Optional[StrictStr] = Field(default=None, description="Source address")
    source_port: Optional[StrictStr] = Field(default=None, description="Source port")
    state: Optional[StrictStr] = Field(default=None, description="State of the rule")
    __properties: ClassVar[List[str]] = ["action", "description", "destination", "destination_port", "icmp_code", "icmp_type", "protocol", "source", "source_port", "state"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NetworkACLRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NetworkACLRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action": obj.get("action"),
            "description": obj.get("description"),
            "destination": obj.get("destination"),
            "destination_port": obj.get("destination_port"),
            "icmp_code": obj.get("icmp_code"),
            "icmp_type": obj.get("icmp_type"),
            "protocol": obj.get("protocol"),
            "source": obj.get("source"),
            "source_port": obj.get("source_port"),
            "state": obj.get("state")
        })
        return _obj


