# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Operation(BaseModel):
    """
    Operation represents a background operation
    """ # noqa: E501
    var_class: Optional[StrictStr] = Field(default=None, description="Type of operation (task, token or websocket)", alias="class")
    created_at: Optional[datetime] = Field(default=None, description="Operation creation time")
    description: Optional[StrictStr] = Field(default=None, description="Description of the operation")
    err: Optional[StrictStr] = Field(default=None, description="Operation error message")
    id: Optional[StrictStr] = Field(default=None, description="UUID of the operation")
    location: Optional[StrictStr] = Field(default=None, description="What cluster member this record was found on")
    may_cancel: Optional[StrictBool] = Field(default=None, description="Whether the operation can be canceled")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Operation specific metadata")
    resources: Optional[Dict[str, Any]] = Field(default=None, description="Affected resources")
    status: Optional[StrictStr] = Field(default=None, description="Status name")
    status_code: Optional[StrictInt] = None
    updated_at: Optional[datetime] = Field(default=None, description="Operation last change")
    __properties: ClassVar[List[str]] = ["class", "created_at", "description", "err", "id", "location", "may_cancel", "metadata", "resources", "status", "status_code", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Operation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Operation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "class": obj.get("class"),
            "created_at": obj.get("created_at"),
            "description": obj.get("description"),
            "err": obj.get("err"),
            "id": obj.get("id"),
            "location": obj.get("location"),
            "may_cancel": obj.get("may_cancel"),
            "metadata": obj.get("metadata"),
            "resources": obj.get("resources"),
            "status": obj.get("status"),
            "status_code": obj.get("status_code"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


