# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ResourcesUSBDeviceInterface(BaseModel):
    """
    ResourcesUSBDeviceInterface represents a USB device interface
    """ # noqa: E501
    var_class: Optional[StrictStr] = Field(default=None, description="Class of USB interface", alias="class")
    class_id: Optional[StrictInt] = Field(default=None, description="ID of the USB interface class")
    driver: Optional[StrictStr] = Field(default=None, description="Kernel driver currently associated with the device")
    driver_version: Optional[StrictStr] = Field(default=None, description="Version of the kernel driver")
    number: Optional[StrictInt] = Field(default=None, description="Interface number")
    subclass: Optional[StrictStr] = Field(default=None, description="Sub class of the interface")
    subclass_id: Optional[StrictInt] = Field(default=None, description="ID of the USB interface sub class")
    __properties: ClassVar[List[str]] = ["class", "class_id", "driver", "driver_version", "number", "subclass", "subclass_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourcesUSBDeviceInterface from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourcesUSBDeviceInterface from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "class": obj.get("class"),
            "class_id": obj.get("class_id"),
            "driver": obj.get("driver"),
            "driver_version": obj.get("driver_version"),
            "number": obj.get("number"),
            "subclass": obj.get("subclass"),
            "subclass_id": obj.get("subclass_id")
        })
        return _obj


