# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.resources_network_card_port_infiniband import ResourcesNetworkCardPortInfiniband
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ResourcesNetworkCardPort(BaseModel):
    """
    ResourcesNetworkCardPort represents a network port on the system
    """ # noqa: E501
    address: Optional[StrictStr] = Field(default=None, description="MAC address")
    auto_negotiation: Optional[StrictBool] = Field(default=None, description="Whether auto negotiation is used")
    id: Optional[StrictStr] = Field(default=None, description="Port identifier (interface name)")
    infiniband: Optional[ResourcesNetworkCardPortInfiniband] = None
    link_detected: Optional[StrictBool] = Field(default=None, description="Whether a link was detected")
    link_duplex: Optional[StrictStr] = Field(default=None, description="Duplex type")
    link_speed: Optional[StrictInt] = Field(default=None, description="Current speed (Mbit/s)")
    port: Optional[StrictInt] = Field(default=None, description="Port number")
    port_type: Optional[StrictStr] = Field(default=None, description="Current port type")
    protocol: Optional[StrictStr] = Field(default=None, description="Transport protocol")
    supported_modes: Optional[List[StrictStr]] = Field(default=None, description="List of supported modes")
    supported_ports: Optional[List[StrictStr]] = Field(default=None, description="List of supported port types")
    transceiver_type: Optional[StrictStr] = Field(default=None, description="Type of transceiver used")
    __properties: ClassVar[List[str]] = ["address", "auto_negotiation", "id", "infiniband", "link_detected", "link_duplex", "link_speed", "port", "port_type", "protocol", "supported_modes", "supported_ports", "transceiver_type"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourcesNetworkCardPort from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of infiniband
        if self.infiniband:
            _dict['infiniband'] = self.infiniband.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourcesNetworkCardPort from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "auto_negotiation": obj.get("auto_negotiation"),
            "id": obj.get("id"),
            "infiniband": ResourcesNetworkCardPortInfiniband.from_dict(obj["infiniband"]) if obj.get("infiniband") is not None else None,
            "link_detected": obj.get("link_detected"),
            "link_duplex": obj.get("link_duplex"),
            "link_speed": obj.get("link_speed"),
            "port": obj.get("port"),
            "port_type": obj.get("port_type"),
            "protocol": obj.get("protocol"),
            "supported_modes": obj.get("supported_modes"),
            "supported_ports": obj.get("supported_ports"),
            "transceiver_type": obj.get("transceiver_type")
        })
        return _obj


