# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.resources_cpu import ResourcesCPU
from pyincusd.models.resources_gpu import ResourcesGPU
from pyincusd.models.resources_load import ResourcesLoad
from pyincusd.models.resources_memory import ResourcesMemory
from pyincusd.models.resources_network import ResourcesNetwork
from pyincusd.models.resources_pci import ResourcesPCI
from pyincusd.models.resources_serial import ResourcesSerial
from pyincusd.models.resources_storage import ResourcesStorage
from pyincusd.models.resources_system import ResourcesSystem
from pyincusd.models.resources_usb import ResourcesUSB
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Resources(BaseModel):
    """
    Resources represents the system hardware resources
    """ # noqa: E501
    cpu: Optional[ResourcesCPU] = None
    gpu: Optional[ResourcesGPU] = None
    load: Optional[ResourcesLoad] = None
    memory: Optional[ResourcesMemory] = None
    network: Optional[ResourcesNetwork] = None
    pci: Optional[ResourcesPCI] = None
    serial: Optional[ResourcesSerial] = None
    storage: Optional[ResourcesStorage] = None
    system: Optional[ResourcesSystem] = None
    usb: Optional[ResourcesUSB] = None
    __properties: ClassVar[List[str]] = ["cpu", "gpu", "load", "memory", "network", "pci", "serial", "storage", "system", "usb"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Resources from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of cpu
        if self.cpu:
            _dict['cpu'] = self.cpu.to_dict()
        # override the default output from pydantic by calling `to_dict()` of gpu
        if self.gpu:
            _dict['gpu'] = self.gpu.to_dict()
        # override the default output from pydantic by calling `to_dict()` of load
        if self.load:
            _dict['load'] = self.load.to_dict()
        # override the default output from pydantic by calling `to_dict()` of memory
        if self.memory:
            _dict['memory'] = self.memory.to_dict()
        # override the default output from pydantic by calling `to_dict()` of network
        if self.network:
            _dict['network'] = self.network.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pci
        if self.pci:
            _dict['pci'] = self.pci.to_dict()
        # override the default output from pydantic by calling `to_dict()` of serial
        if self.serial:
            _dict['serial'] = self.serial.to_dict()
        # override the default output from pydantic by calling `to_dict()` of storage
        if self.storage:
            _dict['storage'] = self.storage.to_dict()
        # override the default output from pydantic by calling `to_dict()` of system
        if self.system:
            _dict['system'] = self.system.to_dict()
        # override the default output from pydantic by calling `to_dict()` of usb
        if self.usb:
            _dict['usb'] = self.usb.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Resources from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cpu": ResourcesCPU.from_dict(obj["cpu"]) if obj.get("cpu") is not None else None,
            "gpu": ResourcesGPU.from_dict(obj["gpu"]) if obj.get("gpu") is not None else None,
            "load": ResourcesLoad.from_dict(obj["load"]) if obj.get("load") is not None else None,
            "memory": ResourcesMemory.from_dict(obj["memory"]) if obj.get("memory") is not None else None,
            "network": ResourcesNetwork.from_dict(obj["network"]) if obj.get("network") is not None else None,
            "pci": ResourcesPCI.from_dict(obj["pci"]) if obj.get("pci") is not None else None,
            "serial": ResourcesSerial.from_dict(obj["serial"]) if obj.get("serial") is not None else None,
            "storage": ResourcesStorage.from_dict(obj["storage"]) if obj.get("storage") is not None else None,
            "system": ResourcesSystem.from_dict(obj["system"]) if obj.get("system") is not None else None,
            "usb": ResourcesUSB.from_dict(obj["usb"]) if obj.get("usb") is not None else None
        })
        return _obj


