# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.resources_storage_disk_partition import ResourcesStorageDiskPartition
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ResourcesStorageDisk(BaseModel):
    """
    ResourcesStorageDisk represents a disk
    """ # noqa: E501
    block_size: Optional[StrictInt] = Field(default=None, description="Block size")
    device: Optional[StrictStr] = Field(default=None, description="Device number")
    device_id: Optional[StrictStr] = Field(default=None, description="Device by-id identifier")
    device_path: Optional[StrictStr] = Field(default=None, description="Device by-path identifier")
    firmware_version: Optional[StrictStr] = Field(default=None, description="Current firmware version")
    id: Optional[StrictStr] = Field(default=None, description="ID of the disk (device name)")
    model: Optional[StrictStr] = Field(default=None, description="Disk model name")
    numa_node: Optional[StrictInt] = Field(default=None, description="NUMA node the disk is a part of")
    partitions: Optional[List[ResourcesStorageDiskPartition]] = Field(default=None, description="List of partitions")
    pci_address: Optional[StrictStr] = Field(default=None, description="PCI address")
    read_only: Optional[StrictBool] = Field(default=None, description="Whether the disk is read-only")
    removable: Optional[StrictBool] = Field(default=None, description="Whether the disk is removable (hot-plug)")
    rpm: Optional[StrictInt] = Field(default=None, description="Rotation speed (RPM)")
    serial: Optional[StrictStr] = Field(default=None, description="Serial number")
    size: Optional[StrictInt] = Field(default=None, description="Total size of the disk (bytes)")
    type: Optional[StrictStr] = Field(default=None, description="Storage type")
    usb_address: Optional[StrictStr] = Field(default=None, description="USB address")
    wwn: Optional[StrictStr] = Field(default=None, description="WWN identifier")
    __properties: ClassVar[List[str]] = ["block_size", "device", "device_id", "device_path", "firmware_version", "id", "model", "numa_node", "partitions", "pci_address", "read_only", "removable", "rpm", "serial", "size", "type", "usb_address", "wwn"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourcesStorageDisk from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in partitions (list)
        _items = []
        if self.partitions:
            for _item_partitions in self.partitions:
                if _item_partitions:
                    _items.append(_item_partitions.to_dict())
            _dict['partitions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourcesStorageDisk from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "block_size": obj.get("block_size"),
            "device": obj.get("device"),
            "device_id": obj.get("device_id"),
            "device_path": obj.get("device_path"),
            "firmware_version": obj.get("firmware_version"),
            "id": obj.get("id"),
            "model": obj.get("model"),
            "numa_node": obj.get("numa_node"),
            "partitions": [ResourcesStorageDiskPartition.from_dict(_item) for _item in obj["partitions"]] if obj.get("partitions") is not None else None,
            "pci_address": obj.get("pci_address"),
            "read_only": obj.get("read_only"),
            "removable": obj.get("removable"),
            "rpm": obj.get("rpm"),
            "serial": obj.get("serial"),
            "size": obj.get("size"),
            "type": obj.get("type"),
            "usb_address": obj.get("usb_address"),
            "wwn": obj.get("wwn")
        })
        return _obj


