# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ResourcesSerialDevice(BaseModel):
    """
    ResourcesSerialDevice represents a serial device
    """ # noqa: E501
    device: Optional[StrictStr] = Field(default=None, description="Device number (major:minor)", json_schema_extra={"examples": ["188:0"]})
    device_id: Optional[StrictStr] = Field(default=None, description="Path to /dev/serial/by-id entry", json_schema_extra={"examples": ["/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AB0J1234-if00-port0"]})
    device_path: Optional[StrictStr] = Field(default=None, description="Path to /dev/serial/by-path entry", json_schema_extra={"examples": ["/dev/serial/by-path/pci-0000:00:14.0-usb-0:2:1.0-port0"]})
    driver: Optional[StrictStr] = Field(default=None, description="kernel driver name (cdc_acm, ftdi_sio, pl2303, cp210x...)", json_schema_extra={"examples": ["cdc_acm"]})
    id: Optional[StrictStr] = Field(default=None, description="Kernel device name (e.g. ttyUSB0, ttyACM0)", json_schema_extra={"examples": ["ttyUSB0"]})
    product: Optional[StrictStr] = Field(default=None, description="USB product name", json_schema_extra={"examples": ["Arduino Uno"]})
    product_id: Optional[StrictStr] = Field(default=None, description="USB product ID", json_schema_extra={"examples": ["0043"]})
    vendor: Optional[StrictStr] = Field(default=None, description="USB vendor name", json_schema_extra={"examples": ["Arduino LLC"]})
    vendor_id: Optional[StrictStr] = Field(default=None, description="USB vendor ID", json_schema_extra={"examples": ["2341"]})
    __properties: ClassVar[List[str]] = ["device", "device_id", "device_path", "driver", "id", "product", "product_id", "vendor", "vendor_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourcesSerialDevice from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourcesSerialDevice from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "device": obj.get("device"),
            "device_id": obj.get("device_id"),
            "device_path": obj.get("device_path"),
            "driver": obj.get("driver"),
            "id": obj.get("id"),
            "product": obj.get("product"),
            "product_id": obj.get("product_id"),
            "vendor": obj.get("vendor"),
            "vendor_id": obj.get("vendor_id")
        })
        return _obj


