# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.resources_system_chassis import ResourcesSystemChassis
from pyincusd.models.resources_system_firmware import ResourcesSystemFirmware
from pyincusd.models.resources_system_motherboard import ResourcesSystemMotherboard
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ResourcesSystem(BaseModel):
    """
    ResourcesSystem represents the system
    """ # noqa: E501
    chassis: Optional[ResourcesSystemChassis] = None
    family: Optional[StrictStr] = Field(default=None, description="System family")
    firmware: Optional[ResourcesSystemFirmware] = None
    motherboard: Optional[ResourcesSystemMotherboard] = None
    product: Optional[StrictStr] = Field(default=None, description="System model")
    serial: Optional[StrictStr] = Field(default=None, description="System serial number")
    sku: Optional[StrictStr] = Field(default=None, description="System nanufacturer SKU LENOVO_MT_20HR_BU_Think_FM_ThinkPad X1 Carbon 5th")
    type: Optional[StrictStr] = Field(default=None, description="System type (unknown, physical, virtual-machine, container, ...)")
    uuid: Optional[StrictStr] = Field(default=None, description="System UUID")
    vendor: Optional[StrictStr] = Field(default=None, description="System vendor")
    version: Optional[StrictStr] = Field(default=None, description="System version")
    __properties: ClassVar[List[str]] = ["chassis", "family", "firmware", "motherboard", "product", "serial", "sku", "type", "uuid", "vendor", "version"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourcesSystem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of chassis
        if self.chassis:
            _dict['chassis'] = self.chassis.to_dict()
        # override the default output from pydantic by calling `to_dict()` of firmware
        if self.firmware:
            _dict['firmware'] = self.firmware.to_dict()
        # override the default output from pydantic by calling `to_dict()` of motherboard
        if self.motherboard:
            _dict['motherboard'] = self.motherboard.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourcesSystem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "chassis": ResourcesSystemChassis.from_dict(obj["chassis"]) if obj.get("chassis") is not None else None,
            "family": obj.get("family"),
            "firmware": ResourcesSystemFirmware.from_dict(obj["firmware"]) if obj.get("firmware") is not None else None,
            "motherboard": ResourcesSystemMotherboard.from_dict(obj["motherboard"]) if obj.get("motherboard") is not None else None,
            "product": obj.get("product"),
            "serial": obj.get("serial"),
            "sku": obj.get("sku"),
            "type": obj.get("type"),
            "uuid": obj.get("uuid"),
            "vendor": obj.get("vendor"),
            "version": obj.get("version")
        })
        return _obj


