# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from pyincusd.models.resources_usb_device_interface import ResourcesUSBDeviceInterface
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ResourcesUSBDevice(BaseModel):
    """
    ResourcesUSBDevice represents a USB device
    """ # noqa: E501
    bus_address: Optional[StrictInt] = Field(default=None, description="USB address (bus)")
    device_address: Optional[StrictInt] = Field(default=None, description="USB address (device)")
    interfaces: Optional[List[ResourcesUSBDeviceInterface]] = Field(default=None, description="List of USB interfaces")
    product: Optional[StrictStr] = Field(default=None, description="Name of the product")
    product_id: Optional[StrictStr] = Field(default=None, description="USB ID of the product")
    serial: Optional[StrictStr] = Field(default=None, description="USB serial number")
    speed: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Transfer speed (Mbit/s)")
    vendor: Optional[StrictStr] = Field(default=None, description="Name of the vendor")
    vendor_id: Optional[StrictStr] = Field(default=None, description="USB ID of the vendor")
    __properties: ClassVar[List[str]] = ["bus_address", "device_address", "interfaces", "product", "product_id", "serial", "speed", "vendor", "vendor_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourcesUSBDevice from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in interfaces (list)
        _items = []
        if self.interfaces:
            for _item_interfaces in self.interfaces:
                if _item_interfaces:
                    _items.append(_item_interfaces.to_dict())
            _dict['interfaces'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourcesUSBDevice from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bus_address": obj.get("bus_address"),
            "device_address": obj.get("device_address"),
            "interfaces": [ResourcesUSBDeviceInterface.from_dict(_item) for _item in obj["interfaces"]] if obj.get("interfaces") is not None else None,
            "product": obj.get("product"),
            "product_id": obj.get("product_id"),
            "serial": obj.get("serial"),
            "speed": obj.get("speed"),
            "vendor": obj.get("vendor"),
            "vendor_id": obj.get("vendor_id")
        })
        return _obj


