# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.server_storage_driver_info import ServerStorageDriverInfo
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ServerEnvironment(BaseModel):
    """
    ServerEnvironment
    """ # noqa: E501
    addresses: Optional[List[StrictStr]] = Field(default=None, description="List of addresses the server is listening on")
    architectures: Optional[List[StrictStr]] = Field(default=None, description="List of architectures supported by the server")
    certificate: Optional[StrictStr] = Field(default=None, description="Server certificate as PEM encoded X509")
    certificate_fingerprint: Optional[StrictStr] = Field(default=None, description="Server certificate fingerprint as SHA256")
    driver: Optional[StrictStr] = Field(default=None, description="List of supported instance drivers (separate by \" | \")")
    driver_version: Optional[StrictStr] = Field(default=None, description="List of supported instance driver versions (separate by \" | \")")
    firewall: Optional[StrictStr] = Field(default=None, description="Current firewall driver")
    kernel: Optional[StrictStr] = Field(default=None, description="OS kernel name")
    kernel_architecture: Optional[StrictStr] = Field(default=None, description="OS kernel architecture")
    kernel_features: Optional[Dict[str, StrictStr]] = Field(default=None, description="Map of kernel features that were tested on startup")
    kernel_version: Optional[StrictStr] = Field(default=None, description="Kernel version")
    lxc_features: Optional[Dict[str, StrictStr]] = Field(default=None, description="Map of LXC features that were tested on startup")
    os_name: Optional[StrictStr] = Field(default=None, description="Name of the operating system (Linux distribution)")
    os_version: Optional[StrictStr] = Field(default=None, description="Version of the operating system (Linux distribution)")
    project: Optional[StrictStr] = Field(default=None, description="Current project name")
    server: Optional[StrictStr] = Field(default=None, description="Server implementation name")
    server_clustered: Optional[StrictBool] = Field(default=None, description="Whether the server is part of a cluster")
    server_event_mode: Optional[StrictStr] = Field(default=None, description="Mode that the event distribution subsystem is operating in on this server. Either \"full-mesh\", \"hub-server\" or \"hub-client\".")
    server_name: Optional[StrictStr] = Field(default=None, description="Server hostname")
    server_pid: Optional[StrictInt] = Field(default=None, description="PID of the daemon")
    server_version: Optional[StrictStr] = Field(default=None, description="Server version")
    storage: Optional[StrictStr] = Field(default=None, description="List of active storage drivers (separate by \" | \")")
    storage_supported_drivers: Optional[List[ServerStorageDriverInfo]] = Field(default=None, description="List of supported storage drivers")
    storage_version: Optional[StrictStr] = Field(default=None, description="List of active storage driver versions (separate by \" | \")")
    __properties: ClassVar[List[str]] = ["addresses", "architectures", "certificate", "certificate_fingerprint", "driver", "driver_version", "firewall", "kernel", "kernel_architecture", "kernel_features", "kernel_version", "lxc_features", "os_name", "os_version", "project", "server", "server_clustered", "server_event_mode", "server_name", "server_pid", "server_version", "storage", "storage_supported_drivers", "storage_version"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServerEnvironment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in storage_supported_drivers (list)
        _items = []
        if self.storage_supported_drivers:
            for _item_storage_supported_drivers in self.storage_supported_drivers:
                if _item_storage_supported_drivers:
                    _items.append(_item_storage_supported_drivers.to_dict())
            _dict['storage_supported_drivers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServerEnvironment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "addresses": obj.get("addresses"),
            "architectures": obj.get("architectures"),
            "certificate": obj.get("certificate"),
            "certificate_fingerprint": obj.get("certificate_fingerprint"),
            "driver": obj.get("driver"),
            "driver_version": obj.get("driver_version"),
            "firewall": obj.get("firewall"),
            "kernel": obj.get("kernel"),
            "kernel_architecture": obj.get("kernel_architecture"),
            "kernel_features": obj.get("kernel_features"),
            "kernel_version": obj.get("kernel_version"),
            "lxc_features": obj.get("lxc_features"),
            "os_name": obj.get("os_name"),
            "os_version": obj.get("os_version"),
            "project": obj.get("project"),
            "server": obj.get("server"),
            "server_clustered": obj.get("server_clustered"),
            "server_event_mode": obj.get("server_event_mode"),
            "server_name": obj.get("server_name"),
            "server_pid": obj.get("server_pid"),
            "server_version": obj.get("server_version"),
            "storage": obj.get("storage"),
            "storage_supported_drivers": [ServerStorageDriverInfo.from_dict(_item) for _item in obj["storage_supported_drivers"]] if obj.get("storage_supported_drivers") is not None else None,
            "storage_version": obj.get("storage_version")
        })
        return _obj


