# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pyincusd.models.storage_volume_backup import StorageVolumeBackup
from pyincusd.models.storage_volume_snapshot import StorageVolumeSnapshot
from pyincusd.models.storage_volume_state import StorageVolumeState
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StorageVolumeFull(BaseModel):
    """
    StorageVolumeFull
    """ # noqa: E501
    backups: Optional[List[StorageVolumeBackup]] = Field(default=None, description="List of backups.")
    config: Optional[Dict[str, Any]] = Field(default=None, description="Storage volume configuration map (refer to doc/storage.md)")
    content_type: Optional[StrictStr] = Field(default=None, description="Volume content type (filesystem or block)")
    created_at: Optional[datetime] = Field(default=None, description="Volume creation timestamp")
    description: Optional[StrictStr] = Field(default=None, description="Description of the storage volume")
    location: Optional[StrictStr] = Field(default=None, description="What cluster member this record was found on")
    name: Optional[StrictStr] = Field(default=None, description="Volume name")
    project: Optional[StrictStr] = Field(default=None, description="Project containing the volume.")
    restore: Optional[StrictStr] = Field(default=None, description="Name of a snapshot to restore")
    snapshots: Optional[List[StorageVolumeSnapshot]] = Field(default=None, description="List of snapshots.")
    state: Optional[StorageVolumeState] = None
    type: Optional[StrictStr] = Field(default=None, description="Volume type")
    used_by: Optional[List[StrictStr]] = Field(default=None, description="List of URLs of objects using this storage volume")
    __properties: ClassVar[List[str]] = ["backups", "config", "content_type", "created_at", "description", "location", "name", "project", "restore", "snapshots", "state", "type", "used_by"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StorageVolumeFull from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in backups (list)
        _items = []
        if self.backups:
            for _item_backups in self.backups:
                if _item_backups:
                    _items.append(_item_backups.to_dict())
            _dict['backups'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in snapshots (list)
        _items = []
        if self.snapshots:
            for _item_snapshots in self.snapshots:
                if _item_snapshots:
                    _items.append(_item_snapshots.to_dict())
            _dict['snapshots'] = _items
        # override the default output from pydantic by calling `to_dict()` of state
        if self.state:
            _dict['state'] = self.state.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StorageVolumeFull from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "backups": [StorageVolumeBackup.from_dict(_item) for _item in obj["backups"]] if obj.get("backups") is not None else None,
            "config": obj.get("config"),
            "content_type": obj.get("content_type"),
            "created_at": obj.get("created_at"),
            "description": obj.get("description"),
            "location": obj.get("location"),
            "name": obj.get("name"),
            "project": obj.get("project"),
            "restore": obj.get("restore"),
            "snapshots": [StorageVolumeSnapshot.from_dict(_item) for _item in obj["snapshots"]] if obj.get("snapshots") is not None else None,
            "state": StorageVolumeState.from_dict(obj["state"]) if obj.get("state") is not None else None,
            "type": obj.get("type"),
            "used_by": obj.get("used_by")
        })
        return _obj


