# coding: utf-8

"""
    Incus external REST API

    This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.

    The version of the OpenAPI document: 1.0
    Contact: lxc-devel@lists.linuxcontainers.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Warning(BaseModel):
    """
    Warning
    """ # noqa: E501
    count: Optional[StrictInt] = Field(default=None, description="The number of times this warning occurred", json_schema_extra={"examples": [1]})
    entity_url: Optional[StrictStr] = Field(default=None, description="The entity affected by this warning", json_schema_extra={"examples": ["/1.0/instances/c1?project=default"]})
    first_seen_at: Optional[datetime] = Field(default=None, description="The first time this warning occurred", json_schema_extra={"examples": ["2021-03-23T17:38:37.753398689-04:00"]})
    last_message: Optional[StrictStr] = Field(default=None, description="The warning message", json_schema_extra={"examples": ["Couldn't find the CGroup blkio.weight, disk priority will be ignored"]})
    last_seen_at: Optional[datetime] = Field(default=None, description="The last time this warning occurred", json_schema_extra={"examples": ["2021-03-23T17:38:37.753398689-04:00"]})
    location: Optional[StrictStr] = Field(default=None, description="What cluster member this warning occurred on", json_schema_extra={"examples": ["server01"]})
    project: Optional[StrictStr] = Field(default=None, description="The project the warning occurred in", json_schema_extra={"examples": ["default"]})
    severity: Optional[StrictStr] = Field(default=None, description="The severity of this warning", json_schema_extra={"examples": ["low"]})
    status: Optional[StrictStr] = Field(default=None, description="Status of the warning (new, acknowledged, or resolved)", json_schema_extra={"examples": ["new"]})
    type: Optional[StrictStr] = Field(default=None, description="Type type of warning", json_schema_extra={"examples": ["Couldn't find CGroup"]})
    uuid: Optional[StrictStr] = Field(default=None, description="UUID of the warning", json_schema_extra={"examples": ["e9e9da0d-2538-4351-8047-46d4a8ae4dbb"]})
    __properties: ClassVar[List[str]] = ["count", "entity_url", "first_seen_at", "last_message", "last_seen_at", "location", "project", "severity", "status", "type", "uuid"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Warning from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Warning from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "count": obj.get("count"),
            "entity_url": obj.get("entity_url"),
            "first_seen_at": obj.get("first_seen_at"),
            "last_message": obj.get("last_message"),
            "last_seen_at": obj.get("last_seen_at"),
            "location": obj.get("location"),
            "project": obj.get("project"),
            "severity": obj.get("severity"),
            "status": obj.get("status"),
            "type": obj.get("type"),
            "uuid": obj.get("uuid")
        })
        return _obj


